### ISSUE TITLE
No issue other than lack of documentation for the not so bright ones (me).

### ISSUE THREAD

**Issue by exxon82** [PTST/O365-HomeAssistant#66]
First I would like to thank you for the work done. This might be the solution I have been looking for. :) The manual installation went fine... but I'm not sure about the configuration of this thing.

I travel a lot for work and I want to use my o365 calendar entries as a base for setting travel_mode in HA. In Outlook I always add an event with the subject "Hotel" at 18:00 to 18:00, same day.
What I want is for the o365 Integration pick this up and set the sensor to on thus letting HA know that I'm not coming home. Would work nice in a bayesian sensor.

This is what I have in my o365_calendar_.yaml. Is this file to be stored in the same folder as configuration.yaml btw?

`- cal_id: xxxx
  entities:
  - device_id: calendar_work
    end_offset: 24
    name: Calendar
    search: Hotel
    start_offset: 0
    track: true`

cal_id... Where to I find this o365 unique generated ID?
start_offset and end_offset... I can't wrap my head around those.

Under Entities in HA I found several calendars, my calendars and shared. I only want the one calendar I define in o365_calendar.yaml. I understand that I have not configured it correctly. Will the calendars I do not set cal_id be removed automatically?

This is what I have in configuration.yaml. I have no need for e-mail, only calendars.
`o365:
  client_secret: "removed"
  client_id: "removed"`

Did I remove too much or is this OK?

Thank you in advance.

**Comment by nagyrobi** [comment]
Did you figure this out?

**Comment by exxon82** [comment]
No, not really.
I haven't had the time to test this by trail and error... but someday... because this add-on seems to do what I want.

**Comment by nagyrobi** [comment]
It actually works. `o365_calendars.yaml` has to be in HA's main config folder just where `configuration.yaml` is. And yes, the documentation is not clear on how to create this file, because it turned out that the component creates it automatically with all the correct values filled in, as soon as it successfully connected to O365. (I succeeded with `alt_auth_flow` option enabled, which is better for installs not reachable from outside).

**Comment by exxon82** [comment]
Thanks for helping out. Removed my o365_calendars.yaml and restarted HA. A new file was automatically generated and populated with data. I will tinker a bit. :)

**Comment by PTST** [comment]
Hello

As stated by @nagyrobi the o365_calendars.yaml file will be automatically generated by the component on start up, including the calendar id, this id should not be updated or modified in any way by you.

Regarding the offset settings, that's for if you want to for example only get events 24h into the future instead of current ones. For the majority of users, this setting should just be ignored.

Your configuration.yaml entry should work.

If you want to hide your other calendars, just set the "track" setting to False. Then they will no longer show up in your entities.
If you just delete them from o365_calendars.yaml, they will be re-added on your next HA restart

I think i got around to all of your questions?
